### PR TITLE
Data Visualization pipeline by Fame

### LINKED ISSUE #1: Data Visualization Pipeline
As a personal open-source project owner, even if our open source has statistical data visualized in the user interfaces of our application. I think if there is any possible way to visualize those data outside.

### PR DESCRIPTION
**Pull request by fame-git**
This is merge request for issues for Data Visualization Pipeline, It will take time until 28 Oct

### CODE REVIEW

**Comment by fame-git** [comment]
I have setup some docker base database with database bench tool but not yet finish on the manual and documenting stuff will catch up soon

**Comment by Monde0** [comment]
Hi, I had a quick look on your branch PR, and it is independent with our tech stack which is fine. This approach is simple and doable. Keep going, it is a good start.

**Comment by fame-git** [comment]
I have push grafana part that will be demonstrating the data visualization. Right now I am on the final stage which is the handover documentation. I will pushed it later.

**Comment by fame-git** [comment]
I push the final version of mine solution. Everything are documented in Infrastructure folder. I will open the merge pull request now.

**Comment by Monde0** [comment]
I look through on your part. It's work fine, stand alone and didn't have any dependency on our stack. I will merge it and close. Well done!

**Pull request merged**
